"""Real, genuine proof of the Git Integration Service
(``P03-S01-M24-T01``) against a real ``git`` binary, a real local bare
repository as the push remote, and a real Postgres container (ADR-0015
— no mocking the database) for the hash-chained ``governance.audit_log``.

Proves: a real workspace directory is genuinely committed to (a real
commit, readable back via ``git log``/``git show``); a real branch is
genuinely created and switched to; a real push genuinely delivers the
commit to a real, separate bare repository (verified by reading the
remote's own refs directly, not merely trusting a success return); a
push to a protected branch is refused *before* any subprocess or remote
contact — the remote receives nothing; a real ``secret://`` credential
is resolved through the real, already-proven
:class:`~ai_os_kernel.secrets_manager.access_broker.AccessBroker` and
injected into the push subprocess's own environment, never appearing in
any recorded audit row; and every mutating operation leaves a real,
hash-chained audit row.
"""

import asyncio
import os
import shutil
import subprocess
import tempfile
from collections.abc import Generator, Sequence
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy.ext.asyncio import AsyncEngine

from ai_os_kernel.git_integration.errors import ProtectedBranchPushRefusedError
from ai_os_kernel.git_integration.models import GitPushPolicy
from ai_os_kernel.git_integration.service import GitIntegrationService
from ai_os_kernel.observability.audit import AuditOutcome, SqlAuditLogWriter
from ai_os_kernel.persistence.engine import build_engine
from ai_os_kernel.sandbox.executor import LocalSubprocessSandbox
from ai_os_kernel.secrets_manager.access_broker import AccessBroker
from ai_os_kernel.secrets_manager.env_provider import EnvSecretProvider
from ai_os_kernel.security_manager.models import Principal, PrincipalType, SecurityContext
from ai_os_kernel.security_manager.permissions import SECRET_ACCESS

REPO_ROOT = Path(__file__).resolve().parents[3]
ALEMBIC_INI = REPO_ROOT / "alembic.ini"

_SECRET_TOKEN = "super-secret-real-token-999"  # noqa: S105 -- test fixture value, not a real credential


def _git_binary() -> str:
    found = shutil.which("git")
    if found is None:
        pytest.skip("git is not available on PATH")
    return found


async def _git(args: Sequence[str], *, cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    """Runs the real, resolved ``git`` binary off the event loop thread
    (this file's own test-driver calls, never the service under test —
    that always goes through the real `LocalSubprocessSandbox`)."""
    return await asyncio.to_thread(
        subprocess.run,
        [_git_binary(), *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        check=True,
    )


@pytest.fixture(scope="module")
def database_url() -> Generator[str, None, None]:
    from tests.integration._postgres_fixture import postgres_container

    with postgres_container() as postgres:
        url = postgres.get_connection_url()
        previous = os.environ.get("AIOS_DATABASE_URL")
        os.environ["AIOS_DATABASE_URL"] = url
        try:
            command.upgrade(Config(str(ALEMBIC_INI)), "head")
            yield url
        finally:
            if previous is None:
                os.environ.pop("AIOS_DATABASE_URL", None)
            else:
                os.environ["AIOS_DATABASE_URL"] = previous


def _admin_context() -> SecurityContext:
    return SecurityContext(
        principal=Principal(
            principal_id="admin-1", principal_type=PrincipalType.USER, roles=frozenset({"admin"})
        ),
        permissions=frozenset({SECRET_ACCESS}),
    )


async def _remote_refs(remote_path: Path) -> str:
    result = await _git(["ls-remote", str(remote_path)])
    return result.stdout


def test_commit_creates_a_real_commit_and_is_audited(database_url: str) -> None:
    async def _run() -> None:
        engine: AsyncEngine = build_engine(database_url)
        try:
            with tempfile.TemporaryDirectory(prefix="aios-git-workspace-") as workdir_str:
                workspace = Path(workdir_str)
                (workspace / "generated.txt").write_text("generated by an agent")

                audit_log = SqlAuditLogWriter(engine)
                service = GitIntegrationService(
                    sandbox=LocalSubprocessSandbox(),
                    audit_log=audit_log,
                    push_policy=GitPushPolicy(protected_branches=frozenset({"main"})),
                    author_name="AI_OS Bot",
                    author_email="bot@ai-os.internal",
                )

                result = await service.commit(
                    workspace=workspace,
                    message="real generated work",
                    actor_id="agent-build",
                    actor_type="agent",
                )

                # Read the real repository back directly — not trusting
                # the service's own return value alone.
                log = await _git(["log", "-1", "--format=%H %an %ae %s"], cwd=workspace)
                assert log.stdout.startswith(result.commit_sha)
                assert "AI_OS Bot bot@ai-os.internal real generated work" in log.stdout

                rows = await audit_log.list_all()
                record = next(r for r in rows if r.event_type == "git.commit.succeeded")
                assert record.principal_id == "agent-build"
                assert record.outcome == AuditOutcome.SUCCESS
                assert record.detail["commit_sha"] == result.commit_sha
        finally:
            await engine.dispose()

    asyncio.run(_run())


def test_create_branch_creates_a_real_branch_and_is_audited(database_url: str) -> None:
    async def _run() -> None:
        engine: AsyncEngine = build_engine(database_url)
        try:
            with tempfile.TemporaryDirectory(prefix="aios-git-workspace-") as workdir_str:
                workspace = Path(workdir_str)
                (workspace / "f.txt").write_text("x")

                audit_log = SqlAuditLogWriter(engine)
                service = GitIntegrationService(
                    sandbox=LocalSubprocessSandbox(),
                    audit_log=audit_log,
                    push_policy=GitPushPolicy(protected_branches=frozenset({"main"})),
                    author_name="AI_OS Bot",
                    author_email="bot@ai-os.internal",
                )
                await service.commit(
                    workspace=workspace, message="c1", actor_id="a", actor_type="agent"
                )

                result = await service.create_branch(
                    workspace=workspace,
                    branch_name="feature/real-branch",
                    actor_id="agent-build",
                    actor_type="agent",
                )
                assert result.created is True

                current = await _git(["branch", "--show-current"], cwd=workspace)
                assert current.stdout.strip() == "feature/real-branch"

                rows = await audit_log.list_all()
                record = next(r for r in rows if r.event_type == "git.branch.create.succeeded")
                assert record.detail["branch"] == "feature/real-branch"
        finally:
            await engine.dispose()

    asyncio.run(_run())


def test_push_delivers_to_a_real_separate_remote_and_is_audited(database_url: str) -> None:
    async def _run() -> None:
        engine: AsyncEngine = build_engine(database_url)
        try:
            with (
                tempfile.TemporaryDirectory(prefix="aios-git-workspace-") as workdir_str,
                tempfile.TemporaryDirectory(prefix="aios-git-remote-") as remote_str,
            ):
                workspace = Path(workdir_str)
                remote = Path(remote_str)
                await _git(["init", "--bare", str(remote)])
                (workspace / "f.txt").write_text("x")

                audit_log = SqlAuditLogWriter(engine)
                service = GitIntegrationService(
                    sandbox=LocalSubprocessSandbox(),
                    audit_log=audit_log,
                    push_policy=GitPushPolicy(protected_branches=frozenset({"main"})),
                    author_name="AI_OS Bot",
                    author_email="bot@ai-os.internal",
                )
                commit_result = await service.commit(
                    workspace=workspace, message="c1", actor_id="a", actor_type="agent"
                )
                await service.create_branch(
                    workspace=workspace,
                    branch_name="feature/push-me",
                    actor_id="a",
                    actor_type="agent",
                )

                push_result = await service.push(
                    workspace=workspace,
                    branch="feature/push-me",
                    remote_url=str(remote),
                    actor_id="agent-build",
                    actor_type="agent",
                )
                assert push_result.branch == "feature/push-me"

                # The real, separate remote genuinely received it —
                # read directly, not through the workspace's own view.
                refs = await _remote_refs(remote)
                assert commit_result.commit_sha in refs
                assert "refs/heads/feature/push-me" in refs

                rows = await audit_log.list_all()
                record = next(r for r in rows if r.event_type == "git.push.succeeded")
                assert record.outcome == AuditOutcome.SUCCESS
                assert record.detail["branch"] == "feature/push-me"
        finally:
            await engine.dispose()

    asyncio.run(_run())


def test_push_to_a_protected_branch_is_refused_and_the_remote_receives_nothing(
    database_url: str,
) -> None:
    async def _run() -> None:
        engine: AsyncEngine = build_engine(database_url)
        try:
            with (
                tempfile.TemporaryDirectory(prefix="aios-git-workspace-") as workdir_str,
                tempfile.TemporaryDirectory(prefix="aios-git-remote-") as remote_str,
            ):
                workspace = Path(workdir_str)
                remote = Path(remote_str)
                await _git(["init", "--bare", str(remote)])
                (workspace / "f.txt").write_text("x")

                audit_log = SqlAuditLogWriter(engine)
                service = GitIntegrationService(
                    sandbox=LocalSubprocessSandbox(),
                    audit_log=audit_log,
                    push_policy=GitPushPolicy(protected_branches=frozenset({"main"})),
                    author_name="AI_OS Bot",
                    author_email="bot@ai-os.internal",
                )
                await service.commit(
                    workspace=workspace, message="c1", actor_id="a", actor_type="agent"
                )
                # The real default branch this repo's own git version
                # creates ("main" or "master") — force it to "main" so
                # this test exercises the real protected-branch path
                # regardless of the runner's own git default.
                await _git(["branch", "-M", "main"], cwd=workspace)

                with pytest.raises(ProtectedBranchPushRefusedError):
                    await service.push(
                        workspace=workspace,
                        branch="main",
                        remote_url=str(remote),
                        actor_id="agent-build",
                        actor_type="agent",
                    )

                # The remote is still genuinely empty — refused before
                # any subprocess touched it, not merely reported as an
                # error after a real push attempt.
                assert await _remote_refs(remote) == ""

                rows = await audit_log.list_all()
                record = next(r for r in rows if r.event_type == "git.push.denied")
                assert record.outcome == AuditOutcome.DENIED
                assert record.detail["reason"] == "protected_branch"
        finally:
            await engine.dispose()

    asyncio.run(_run())


def test_push_with_a_real_credential_resolves_it_and_never_leaks_it(database_url: str) -> None:
    async def _run() -> None:
        engine: AsyncEngine = build_engine(database_url)
        try:
            with (
                tempfile.TemporaryDirectory(prefix="aios-git-workspace-") as workdir_str,
                tempfile.TemporaryDirectory(prefix="aios-git-remote-") as remote_str,
            ):
                workspace = Path(workdir_str)
                remote = Path(remote_str)
                await _git(["init", "--bare", str(remote)])
                (workspace / "f.txt").write_text("x")

                audit_log = SqlAuditLogWriter(engine)
                provider = EnvSecretProvider(env={"AIOS_SECRET_GIT_TOKEN": _SECRET_TOKEN})
                broker = AccessBroker(provider=provider, audit_log=audit_log)
                service = GitIntegrationService(
                    sandbox=LocalSubprocessSandbox(),
                    audit_log=audit_log,
                    push_policy=GitPushPolicy(protected_branches=frozenset({"main"})),
                    author_name="AI_OS Bot",
                    author_email="bot@ai-os.internal",
                    secret_broker=broker,
                )
                await service.commit(
                    workspace=workspace, message="c1", actor_id="a", actor_type="agent"
                )
                await service.create_branch(
                    workspace=workspace,
                    branch_name="feature/with-credential",
                    actor_id="a",
                    actor_type="agent",
                )

                await service.push(
                    workspace=workspace,
                    branch="feature/with-credential",
                    remote_url=str(remote),
                    credential_reference="secret://env/git-token",
                    security_context=_admin_context(),
                    actor_id="agent-build",
                    actor_type="agent",
                )

                # The real, separate remote genuinely received the push
                # — the credential mechanism ran for real and did not
                # block the operation.
                assert "refs/heads/feature/with-credential" in await _remote_refs(remote)

                # The one property that matters most: the real secret
                # value is never anywhere in the real audit trail — not
                # in this service's own rows, and not in the
                # already-proven AccessBroker's own resolution row
                # either (both write to the same table here).
                rows = await audit_log.list_all()
                assert any(r.event_type == "secret.access.allowed" for r in rows)
                assert any(r.event_type == "git.push.succeeded" for r in rows)
                for record in rows:
                    assert _SECRET_TOKEN not in str(record.detail)
        finally:
            await engine.dispose()

    asyncio.run(_run())
