/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pending Approvals */
        get: operations["list_pending_approvals_api_v1_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Approval History
         * @description api_architecture.md §6.2's own documented ``GET
         *     /api/v1/approvals/history`` ("Past decisions") — the last of the 4
         *     named Approvals endpoints, now real.
         */
        get: operations["list_approval_history_api_v1_approvals_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Approval
         * @description ``api_architecture.md`` §6.2's own documented ``GET
         *     /api/v1/approvals/{id}`` ("Detail incl. decision context") — real
         *     now, closing a real gap ``aios approve show``
         *     (``P06-S04-M38-T01``) disclosed as blocked pending "no
         *     get-approval-by-id route." The underlying read
         *     (``SqlApprovalRepository.get_by_id``) already existed — used
         *     internally by ``decide_approval`` above — this route only exposes
         *     it directly, over the same ``APPROVAL_READ`` permission the list
         *     route already gates on.
         */
        get: operations["get_approval_api_v1_approvals__approval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Effective Config */
        get: operations["get_effective_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Config */
        patch: operations["update_config_api_v1_config_patch"];
        trace?: never;
    };
    "/api/v1/config/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feature Flags */
        get: operations["get_feature_flags_api_v1_config_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/cost-and-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cost And Quality Report */
        get: operations["get_cost_and_quality_report_api_v1_evaluation_cost_and_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Live
         * @description Liveness probe. Must never depend on an external service — a brief
         *     dependency blip must not cause a container restart (Deployment
         *     Architecture §6).
         */
        get: operations["health_live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Readiness probe. Returns HTTP 200 for "ready"/"degraded" — a
         *     reduced-capability Kernel can still usefully serve some traffic —
         *     and HTTP 503 for "not_ready": at least one critical component (the
         *     database, today — see ``ai_os_kernel.health.service``'s own
         *     docstring for why it is a real hard dependency, not an assumed one)
         *     has failed, and every functional route in this codebase already
         *     independently 503s without one anyway.
         */
        get: operations["health_ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Packs */
        get: operations["list_packs_api_v1_packs_get"];
        put?: never;
        /** Register Pack */
        post: operations["register_pack_api_v1_packs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packs/{pack_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pack */
        get: operations["get_pack_api_v1_packs__pack_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packs/{pack_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Pack */
        post: operations["activate_pack_api_v1_packs__pack_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packs/{pack_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Pack */
        post: operations["deactivate_pack_api_v1_packs__pack_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/security/role-grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant Role */
        post: operations["grant_role_api_v1_security_role_grants_post"];
        /** Revoke Role */
        delete: operations["revoke_role_api_v1_security_role_grants_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["get_version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflows */
        get: operations["list_workflows_api_v1_workflows_get"];
        put?: never;
        /** Start Workflow */
        post: operations["start_workflow_api_v1_workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/se.delivery_pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Delivery Pipeline */
        post: operations["trigger_delivery_pipeline_api_v1_workflows_se_delivery_pipeline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow */
        get: operations["get_workflow_api_v1_workflows__workflow_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/approvals/{approval_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Approval */
        post: operations["decide_approval_api_v1_workflows__workflow_id__approvals__approval_id__decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow Events */
        get: operations["get_workflow_events_api_v1_workflows__workflow_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow Steps */
        get: operations["get_workflow_steps_api_v1_workflows__workflow_id__steps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Approval
         * @description One ``workflow.approvals`` row (data_model.md §4.5).
         */
        Approval: {
            /** Approval Class */
            approval_class: string;
            /** Approval Id */
            approval_id: string;
            /** Context Digest */
            context_digest: string;
            /** Decided At */
            decided_at: string | null;
            /** Decided By */
            decided_by: string | null;
            /** Decision Comment */
            decision_comment: string | null;
            /** Description */
            description: string;
            /** Expires At */
            expires_at: string | null;
            /** Options */
            options: string[];
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Status */
            status: string;
            /** Step Id */
            step_id: string;
            /** Title */
            title: string;
            /** Workflow Id */
            workflow_id: string;
        };
        /**
         * ApprovalHistoryResponse
         * @description api_architecture.md §9's documented collection envelope
         *     (``{"items": [...], "next_cursor": "…" | null}``), the same real
         *     shape ``GET /workflows`` already uses — see
         *     :meth:`~ai_os_kernel.workflow_engine.human_approval.
         *     SqlApprovalRepository.list_decided`'s own docstring for why this
         *     route needs it and ``list_pending`` above deliberately does not.
         */
        ApprovalHistoryResponse: {
            /** Items */
            items: components["schemas"]["Approval"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ComponentStatus */
        ComponentStatus: {
            /**
             * Critical
             * @default false
             */
            critical: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
        };
        /**
         * CostAndQualityReport
         * @description The real, queryable artifact this ticket's own Output names:
         *     "Reconciling breakdowns" — every real cost dimension FR-095 names,
         *     plus FR-094's own real gate-failure frequency.
         */
        CostAndQualityReport: {
            /** By Agent */
            by_agent: components["schemas"]["CostBreakdownEntry"][];
            /** By Model */
            by_model: components["schemas"]["CostBreakdownEntry"][];
            /** By Pack */
            by_pack: components["schemas"]["CostBreakdownEntry"][];
            /** By Workflow */
            by_workflow: components["schemas"]["CostBreakdownEntry"][];
            /** Gate Failures */
            gate_failures: components["schemas"]["GateFailureSummaryEntry"][];
        };
        /**
         * CostBreakdownEntry
         * @description One real dimension value's own aggregated cost — e.g. one real
         *     `model_id`, or one real `pack_id`, together with every real call
         *     this project has ever recorded against it.
         */
        CostBreakdownEntry: {
            /** Call Count */
            call_count: number;
            /** Dimension Value */
            dimension_value: string;
            /** Total Cost Usd */
            total_cost_usd: string;
            /** Total Input Tokens */
            total_input_tokens: number;
            /** Total Output Tokens */
            total_output_tokens: number;
        };
        /**
         * DecideApprovalRequest
         * @description Mirrors :class:`~ai_os_kernel.workflow_engine.human_approval.
         *     Decision` — only ``approved``/``rejected`` are real decisions today
         *     (``human_approval.py``'s own disclosed scope: no ``changes_requested``
         *     handling exists).
         */
        DecideApprovalRequest: {
            /** Comment */
            comment?: string | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
        };
        /**
         * DecideApprovalResponse
         * @description The real, recorded decision, plus whether — and how — this
         *     specific workflow was genuinely resumed. ``resumed`` is ``False``
         *     whenever the decided workflow is not ``se.delivery_pipeline`` (the
         *     one real, wired resumption target today) — a real, honest signal,
         *     not a placeholder.
         */
        DecideApprovalResponse: {
            /** Approval Id */
            approval_id: string;
            /** Decided By */
            decided_by: string;
            /** Decision */
            decision: string;
            /** Resumed */
            resumed: boolean;
            /** Resumed Error */
            resumed_error: string | null;
            resumed_outcome: components["schemas"]["WorkflowRunOutcome"] | null;
            /** Workflow Id */
            workflow_id: string;
        };
        /**
         * FeatureFlagState
         * @description One real, resolved feature flag — declared by at least one
         *     activated pack's own manifest, current value resolved through the
         *     identical layered precedence every other real caller uses.
         */
        FeatureFlagState: {
            /** Enabled */
            enabled: boolean;
            /** Name */
            name: string;
        };
        /**
         * GateFailureSummaryEntry
         * @description One real gate's own real failure count — FR-094's "most
         *     frequent failures," ordered by the caller (descending count).
         */
        GateFailureSummaryEntry: {
            /** Count */
            count: number;
            /** Gate Id */
            gate_id: string;
            /** Status */
            status: string;
        };
        /**
         * GrantRoleRequest
         * @description Mirrors :meth:`RoleAdministrationService.grant`'s own keyword
         *     arguments exactly — no parallel request shape.
         */
        GrantRoleRequest: {
            /** Principal Id */
            principal_id: string;
            /** Reason */
            reason: string;
            /** Role */
            role: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PackLifecycleActionRequest
         * @description Shared by activate/deactivate — just ``reason``. ``actor`` is
         *     deliberately not a client-supplied field: it is the authenticated
         *     principal's own id, the same "who did this comes from
         *     authentication, not client-declared honesty" convention
         *     ``start_workflow`` already established.
         */
        PackLifecycleActionRequest: {
            /** Reason */
            reason: string;
        };
        /**
         * PackRecord
         * @description One ``catalog.packs`` row, as read back immediately after a
         *     register/activate/deactivate call, or by a plain lookup.
         */
        PackRecord: {
            /** Activated At */
            activated_at: string | null;
            /** Health */
            health: {
                [key: string]: unknown;
            } | null;
            /** Installed At */
            installed_at: string | null;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Min Kernel Version */
            min_kernel_version: string;
            /** Pack Id */
            pack_id: string;
            /** Sdk Version */
            sdk_version: string;
            state: components["schemas"]["PackState"];
            /** Version */
            version: string;
        };
        /**
         * PackState
         * @description One state in the canonical Capability Pack lifecycle. Only
         *     ``ACTIVATED`` is meaningful to
         *     :class:`~ai_os_kernel.workflow_engine.registry.SqlAgentRegistry`/
         *     :class:`~ai_os_kernel.workflow_engine.registry.SqlToolRegistry`
         *     today — the other seven exist here only so this enum is a complete,
         *     honest mirror of the documented lifecycle, not a partial one
         *     reverse-engineered from this step's own narrow need.
         * @enum {string}
         */
        PackState: "discovered" | "validated" | "installed" | "configured" | "activated" | "deactivated" | "failed" | "uninstalled";
        /**
         * PendingApprovalsResponse
         * @description api_architecture.md §6.2's own documented ``GET /api/v1/approvals``
         *     ("Pending approvals") — the real gap this module's own sibling,
         *     ``human_approval.py``, named as "real, separate, later work"
         *     (``P06-S03-M39-T02``). Deliberately unpaginated — see
         *     :meth:`~ai_os_kernel.workflow_engine.human_approval.
         *     SqlApprovalRepository.list_pending`'s own docstring for why the
         *     pending queue does not need the cursor-paginated envelope
         *     ``GET /workflows`` uses.
         */
        PendingApprovalsResponse: {
            /** Approvals */
            approvals: components["schemas"]["Approval"][];
        };
        /**
         * PlatformConfig
         * @description Immutable, fully resolved configuration for one Kernel process.
         *
         *     ``env`` and ``role`` are bootstrap identity — how this process was
         *     started — never values a configuration file may set. They are
         *     always supplied explicitly by
         *     :class:`~ai_os_kernel.configuration_manager.loader.ConfigurationManager`,
         *     not read from YAML (see
         *     ``docs/03_architecture/services/configuration_management.md`` §3.3).
         */
        PlatformConfig: {
            /** Audit Chain Verification Interval Seconds */
            audit_chain_verification_interval_seconds?: number | null;
            /** Capability Pack Dirs */
            capability_pack_dirs?: string[];
            /** Cost Anomaly Check Interval Seconds */
            cost_anomaly_check_interval_seconds?: number | null;
            /** Env */
            env: string;
            /**
             * Host
             * @default 127.0.0.1
             */
            host: string;
            /** Lease Reap Interval Seconds */
            lease_reap_interval_seconds?: number | null;
            /**
             * Log Level
             * @default INFO
             */
            log_level: string;
            /**
             * Manifest Schema Path
             * @default platform_sdk/schemas/manifest.schema.json
             */
            manifest_schema_path: string;
            /** Notification Webhook Url */
            notification_webhook_url?: string | null;
            /** Oidc Audience */
            oidc_audience?: string | null;
            /** Oidc Issuer */
            oidc_issuer?: string | null;
            /** Oidc Jwks Uri */
            oidc_jwks_uri?: string | null;
            /** Pack Health Poll Interval Seconds */
            pack_health_poll_interval_seconds?: number | null;
            /**
             * Port
             * @default 8000
             */
            port: number;
            /** Role */
            role: string;
            /** Scheduler Interval Seconds */
            scheduler_interval_seconds?: number | null;
            /** Worker Poll Interval Seconds */
            worker_poll_interval_seconds?: number | null;
        };
        /** ReadinessReport */
        ReadinessReport: {
            /** Components */
            components: components["schemas"]["ComponentStatus"][];
            /** Status */
            status: string;
        };
        /**
         * RegisterPackRequest
         * @description Deliberately just the fields
         *     :meth:`~ai_os_kernel.capability_manager.repository.PackLifecycleRepository.register`
         *     already takes — no discovery, no manifest schema validation (that
         *     remains the Manifest Loader's job at a different point in the
         *     pipeline this step does not touch).
         */
        RegisterPackRequest: {
            /** Manifest */
            manifest?: {
                [key: string]: unknown;
            };
            /** Min Kernel Version */
            min_kernel_version: string;
            /** Pack Id */
            pack_id: string;
            /** Reason */
            reason: string;
            /** Sdk Version */
            sdk_version: string;
            /** Version */
            version: string;
        };
        /**
         * RevokeRoleRequest
         * @description Mirrors :meth:`RoleAdministrationService.revoke`'s own keyword
         *     arguments exactly — no parallel request shape.
         */
        RevokeRoleRequest: {
            /** Principal Id */
            principal_id: string;
            /** Reason */
            reason: string;
            /** Role */
            role: string;
        };
        /**
         * RoleGrant
         * @description One ``security.role_grants`` row (data_model.md §9a.1).
         */
        RoleGrant: {
            /** Grant Id */
            grant_id: string;
            /**
             * Granted At
             * Format: date-time
             */
            granted_at: string;
            /** Granted By */
            granted_by: string;
            /** Granted Reason */
            granted_reason: string;
            /** Principal Id */
            principal_id: string;
            /** Revoked At */
            revoked_at: string | null;
            /** Revoked By */
            revoked_by: string | null;
            /** Revoked Reason */
            revoked_reason: string | null;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /**
         * StartWorkflowRequest
         * @description Deliberately just ``inputs`` — see module docstring for the
         *     fields the full documented contract has that this does not yet.
         */
        StartWorkflowRequest: {
            /** Inputs */
            inputs?: {
                [key: string]: unknown;
            };
        };
        /**
         * StartWorkflowResponse
         * @description A reduced, JSON-safe projection of
         *     :class:`~ai_os_kernel.workflow_engine.advance_runner.WorkflowRunResult`
         *     — not that model itself, since its ``last_instance``/``error`` fields
         *     carry internal shapes (a full ``WorkflowInstance``, a raw exception
         *     object) that are not this endpoint's documented response and should
         *     not cross the API boundary unfiltered.
         */
        StartWorkflowResponse: {
            /** Error */
            error: string | null;
            /** Iterations */
            iterations: number;
            outcome: components["schemas"]["WorkflowRunOutcome"];
            /** Workflow Id */
            workflow_id: string;
        };
        /**
         * StepType
         * @description The eight Supported Step Types (workflow_architecture.md).
         *     ``FOREACH`` added `P08-S02-M30-T01` — ADR-0021's own "dynamic
         *     decomposition without dynamic control flow" pattern: a
         *     ``technical-planner`` plan artifact drives a bounded fan-out of a
         *     declared sub-workflow, one child instance per item, never an
         *     unbounded or model-chosen loop.
         * @enum {string}
         */
        StepType: "agent" | "tool" | "decision" | "parallel" | "sub_workflow" | "quality_gate" | "human_approval" | "foreach";
        /**
         * TriggerDeliveryPipelineRequest
         * @description Mirrors ``capability_packs/software-engineering/workflows/delivery_pipeline.yaml``'s
         *     own declared ``inputs`` schema exactly
         *     (``ai_os_pack_software_engineering.workflows.models:PipelineInput``).
         */
        TriggerDeliveryPipelineRequest: {
            /**
             * Requirement
             * @description The raw software requirement or ask to design, build, test, and document — analyzed and refined by Requirements Analyst before Architecture ever sees it.
             */
            requirement: string;
            /**
             * Specification
             * @description An optional, additional structured Markdown specification (FR-030, `P03-S03-M30-T02`) — parsed into validated requirement items by Requirements Analyst. `requirement` stays required and unaffected; omitting this field changes nothing for any existing caller.
             */
            specification?: string | null;
        };
        /**
         * TriggerDeliveryPipelineResponse
         * @description A reduced, JSON-safe projection of
         *     :class:`~ai_os_kernel.workflow_engine.advance_runner.WorkflowRunResult`
         *     — the identical shape :class:`~ai_os_kernel.routes.workflows.StartWorkflowResponse`
         *     already establishes — extended with ``documentation_path``, this
         *     pipeline's own real, known output field (``None`` unless the run
         *     genuinely completed and a real documentation artifact path was
         *     persisted).
         */
        TriggerDeliveryPipelineResponse: {
            /** Documentation Path */
            documentation_path: string | null;
            /** Error */
            error: string | null;
            /** Iterations */
            iterations: number;
            outcome: components["schemas"]["WorkflowRunOutcome"];
            /** Workflow Id */
            workflow_id: string;
        };
        /**
         * UpdateConfigRequest
         * @description ``PATCH /config``'s own body — deliberately just the fields
         *     :meth:`RuntimeOverrideStore.apply` already takes. ``changed_by`` is
         *     not a client-supplied field: it is the authenticated principal's
         *     own id, the same "who did this comes from authentication" convention
         *     ``PackLifecycleActionRequest`` already establishes.
         */
        UpdateConfigRequest: {
            /** Config Key */
            config_key: string;
            /** New Value */
            new_value: unknown;
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkflowEventRecord
         * @description One ``workflow_events`` row.
         *
         *     ``event_type`` is a plain ``str``, not an enum: data_model.md §4.2
         *     lists example values (``workflow.started``, ``step.started``, …)
         *     ending in an ellipsis — an explicitly open-ended, illustrative set,
         *     not a closed list like ``step_type``'s seven values. Enumerating
         *     one here would invent a closed vocabulary the doc deliberately
         *     does not declare, and the table itself has no ``CHECK`` constraint
         *     on this column either.
         */
        WorkflowEventRecord: {
            /** Agent Id */
            agent_id: string | null;
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Schema Version */
            schema_version: number;
            /** Seq */
            seq: number;
            /** Step Id */
            step_id: string | null;
            /** Trace Id */
            trace_id: string | null;
            /** Workflow Id */
            workflow_id: string;
        };
        /**
         * WorkflowInstance
         * @description One ``workflow_instances`` row, as read back immediately after
         *     creation.
         */
        WorkflowInstance: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Step Id */
            current_step_id: string | null;
            /** Definition Id */
            definition_id: string;
            /** Definition Version */
            definition_version: string;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
            /** Experiment Id */
            experiment_id: string | null;
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
            /** Last Event Seq */
            last_event_seq: number;
            /** Outputs */
            outputs: {
                [key: string]: unknown;
            } | null;
            /** Principal Id */
            principal_id: string;
            /** Principal Permissions */
            principal_permissions: string[] | null;
            /** Run Manifest Id */
            run_manifest_id: string | null;
            /** Scheduled At */
            scheduled_at: string | null;
            status: components["schemas"]["WorkflowInstanceStatus"];
            /** Total Cost Usd */
            total_cost_usd: string;
            /** Total Tokens */
            total_tokens: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Workflow Id */
            workflow_id: string;
        };
        /**
         * WorkflowInstanceStatus
         * @description The canonical nine-state list (workflow_engine.md §7).
         * @enum {string}
         */
        WorkflowInstanceStatus: "created" | "running" | "waiting_for_human" | "waiting_for_retry" | "quality_gate_failed" | "compensating" | "completed" | "failed" | "cancelled";
        /**
         * WorkflowListResponse
         * @description api_architecture.md §9's documented collection envelope:
         *     ``{"items": [...], "next_cursor": "…" | null}``.
         */
        WorkflowListResponse: {
            /** Items */
            items: components["schemas"]["WorkflowInstance"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * WorkflowRunOutcome
         * @description How a :meth:`WorkflowAdvanceRunner.run_to_completion` call ended.
         * @enum {string}
         */
        WorkflowRunOutcome: "completed" | "max_iterations_reached" | "failed" | "waiting_for_human";
        /**
         * WorkflowStepRecord
         * @description One ``workflow_steps`` row.
         *
         *     ``status`` is a plain ``str``, not an enum: unlike
         *     ``workflow_instances.status``, data_model.md §4.3 gives
         *     ``workflow_steps.status`` no canonical value list, so typing it as
         *     an enum here would invent one. ``step_type`` *is* typed as
         *     :class:`StepType` — its seven values are already documented
         *     (workflow_architecture.md's Supported Step Types) and already
         *     enforced by the table's own ``CHECK`` constraint.
         */
        WorkflowStepRecord: {
            /** Agent Id */
            agent_id: string | null;
            /** Attempt */
            attempt: number;
            /** Completed At */
            completed_at: string | null;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
            /** Idempotency Key */
            idempotency_key: string;
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
            /** Model Alias */
            model_alias: string | null;
            /** Outputs */
            outputs: {
                [key: string]: unknown;
            } | null;
            /** Prompt Id */
            prompt_id: string | null;
            /** Prompt Version */
            prompt_version: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Step Id */
            step_id: string;
            /** Step Name */
            step_name: string;
            step_type: components["schemas"]["StepType"];
            /** Tool Id */
            tool_id: string | null;
            /** Usage */
            usage: {
                [key: string]: unknown;
            };
            /** Workflow Id */
            workflow_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_pending_approvals_api_v1_approvals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingApprovalsResponse"];
                };
            };
        };
    };
    list_approval_history_api_v1_approvals_history_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_api_v1_approvals__approval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_effective_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformConfig"];
                };
            };
        };
    };
    update_config_api_v1_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feature_flags_api_v1_config_flags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagState"][];
                };
            };
        };
    };
    get_cost_and_quality_report_api_v1_evaluation_cost_and_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostAndQualityReport"];
                };
            };
        };
    };
    health_live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessReport"];
                };
            };
        };
    };
    list_packs_api_v1_packs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackRecord"][];
                };
            };
        };
    };
    register_pack_api_v1_packs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pack_api_v1_packs__pack_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_pack_api_v1_packs__pack_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackLifecycleActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_pack_api_v1_packs__pack_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackLifecycleActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_role_api_v1_security_role_grants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleGrant"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_role_api_v1_security_role_grants_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleGrant"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_workflows_api_v1_workflows_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_workflow_api_v1_workflows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartWorkflowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartWorkflowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_delivery_pipeline_api_v1_workflows_se_delivery_pipeline_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerDeliveryPipelineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerDeliveryPipelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_api_v1_workflows__workflow_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowInstance"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_approval_api_v1_workflows__workflow_id__approvals__approval_id__decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecideApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_events_api_v1_workflows__workflow_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowEventRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_steps_api_v1_workflows__workflow_id__steps_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStepRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
