"""One-time seeder that materialises the initial Task tickets.

Run once (Phase R2). After this, the generated ``.md`` ticket files under
``docs/19_roadmap/tickets/`` are the hand-authored source of truth and
this script is a historical record of how they were first populated — it
is **not** re-run as part of any normal step, and it refuses to overwrite
an existing ticket unless ``--force`` is passed.

Every ``done``/``partial`` status below was set from real evidence
gathered in the Phase R1 audit (source inspection, the feature inventory
completion table, and the roadmap's own per-deliverable markers), not
from assumption. The ``evidence:`` field on each such ticket names the
real path that substantiates it.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from scripts.roadmap.stages import MODULE_PATHS

REPO_ROOT = Path(__file__).resolve().parents[2]
TICKETS_ROOT = REPO_ROOT / "docs" / "19_roadmap" / "tickets"

# (title, status, goal, input, output, depends_on, evidence)
T = tuple[str, str, str, str, str, list[str], str]

# phase -> stage -> module -> [tasks]
SEED: dict[int, dict[int, dict[int, list[T]]]] = {
    1: {
        1: {
            40: [
                (
                    "uv workspace and committed lockfile",
                    "done",
                    "All distributions resolve from one committed `uv.lock` (ADR-0009).",
                    "pyproject.toml workspace members.",
                    "Reproducible `uv sync --frozen`.",
                    [],
                    "uv.lock",
                ),
                (
                    "Composition root with lifecycle ordering",
                    "done",
                    "One explicit composition root wires the Kernel (ADR-0010).",
                    "PlatformConfig.",
                    "A built FastAPI app with ordered startup/shutdown.",
                    [],
                    "kernel/src/ai_os_kernel/bootstrap.py",
                ),
                (
                    "Alembic baseline and Compose services",
                    "done",
                    "Schema migrations and dev Postgres/Redis exist and apply cleanly.",
                    "Alembic revisions.",
                    "29 migrations applying up/down/up.",
                    [],
                    "kernel/alembic/versions",
                ),
                (
                    "Runtime container image",
                    "todo",
                    "Produce a real runnable image for the api and worker processes.",
                    "The uv workspace.",
                    "A Dockerfile building a working image.",
                    [],
                    "",
                ),
            ],
        },
        2: {
            1: [
                (
                    "Layered precedence resolution (3 of 7)",
                    "partial",
                    "Resolve configuration through the documented precedence order.",
                    "Defaults, file, environment.",
                    "One resolved, validated config object.",
                    [],
                    "kernel/src/ai_os_kernel/config",
                ),
                (
                    "Schema validation of resolved config",
                    "done",
                    "Reject an invalid configuration at startup, not at first use.",
                    "A candidate config mapping.",
                    "Validated model, or a clear error.",
                    [],
                    "kernel/src/ai_os_kernel/config",
                ),
                (
                    "Pack-defaults precedence layer",
                    "todo",
                    "Let an activated pack contribute its own default values.",
                    "Pack manifest defaults.",
                    "Layer inserted at the documented position.",
                    [],
                    "",
                ),
                (
                    "Runtime-overrides precedence layer",
                    "todo",
                    "Allow a runtime override without a process restart.",
                    "An override request.",
                    "Layer applied above file config.",
                    [],
                    "",
                ),
                (
                    "Experiment-overrides precedence layer",
                    "todo",
                    "Isolate per-experiment configuration from the base config.",
                    "An experiment definition.",
                    "Overrides scoped to one run.",
                    [],
                    "",
                ),
                (
                    "Secrets layer integration",
                    "todo",
                    "Resolve `secret://` references as a real precedence layer.",
                    "Config values holding secret references.",
                    "Resolved values, never logged.",
                    [],
                    "",
                ),
                (
                    "Feature flags",
                    "todo",
                    "Toggle behaviour without a deploy.",
                    "Flag definitions.",
                    "Readable flag state.",
                    [],
                    "",
                ),
                (
                    "Configuration change-audit trail",
                    "todo",
                    "Record who changed which configuration value and when.",
                    "A config mutation.",
                    "An audit record.",
                    [],
                    "",
                ),
            ],
            19: [
                (
                    "env secret backend",
                    "done",
                    "Resolve `secret://env/...` references from the environment.",
                    "A secret reference URI.",
                    "The resolved value, never logged.",
                    [],
                    "kernel/src/ai_os_kernel/secrets_manager/env_provider.py",
                ),
                (
                    "Reference-only secret handling",
                    "done",
                    "Secrets are passed by reference, never inlined into config or state.",
                    "A `secret://` URI.",
                    "No secret value in any log, event, or audit payload.",
                    [],
                    "kernel/src/ai_os_kernel/secrets_manager",
                ),
                (
                    "file secret backend",
                    "todo",
                    "Resolve secrets from a mounted file backend (ADR-0024).",
                    "A file-backed reference.",
                    "The resolved value.",
                    [],
                    "",
                ),
                (
                    "Access broker",
                    "todo",
                    "Gate which principal may resolve which secret.",
                    "Principal plus reference.",
                    "Allow or deny, audited.",
                    [],
                    "",
                ),
                (
                    "TTL cache and rotation",
                    "todo",
                    "Cache resolved secrets with expiry and support rotation.",
                    "A resolved secret.",
                    "Bounded-lifetime cache entry.",
                    [],
                    "",
                ),
                (
                    "Prompt-assembly secret leak scan",
                    "todo",
                    "Refuse to send an assembled prompt containing a resolved secret.",
                    "An assembled prompt.",
                    "Blocked send plus an audit record.",
                    [],
                    "",
                ),
            ],
        },
        3: {
            2: [
                (
                    "JSON Schema manifest validation",
                    "done",
                    "Validate a pack manifest and fail closed on any violation.",
                    "A manifest.yaml.",
                    "Validated manifest, or a specific error and no registration.",
                    [],
                    "kernel/src/ai_os_kernel/manifest_loader",
                ),
                (
                    "Filesystem-scan pack discovery",
                    "done",
                    "Find candidate packs by scanning configured directories.",
                    "capability_pack_dirs.",
                    "A discovery report.",
                    [],
                    "kernel/src/ai_os_kernel/manifest_loader",
                ),
                (
                    "Entry-point discovery",
                    "todo",
                    "Discover installed packs via Python entry points (ADR-0009).",
                    "Installed distributions.",
                    "Discovered packs without a filesystem scan.",
                    [],
                    "",
                ),
                (
                    "Remaining semantic manifest rules",
                    "todo",
                    "Enforce workflow-definition existence, circularity, and SDK version range.",
                    "A schema-valid manifest.",
                    "Rejection of semantically invalid manifests.",
                    [],
                    "",
                ),
            ],
            28: [
                (
                    "Versioned manifest JSON Schema",
                    "done",
                    "One authoritative, versioned schema every pack validates against.",
                    "Pack manifest documents.",
                    "Accept/reject with a specific error.",
                    [],
                    "platform_sdk/schemas/manifest.schema.json",
                ),
                (
                    "Signed-manifest fields",
                    "blocked",
                    "OUT OF V1 SCOPE (functional_requirements.md §10). Recorded, not scheduled.",
                    "n/a.",
                    "n/a.",
                    [],
                    "",
                ),
            ],
        },
        4: {
            3: [
                (
                    "Liveness and readiness endpoints",
                    "done",
                    "Report process liveness and component readiness over HTTP.",
                    "Registered component checks.",
                    "/health/live and /health/ready.",
                    [],
                    "kernel/src/ai_os_kernel/routes/health.py",
                ),
                (
                    "Database as a hard readiness dependency",
                    "done",
                    "Return 503 when the database is genuinely unreachable.",
                    "A real SELECT 1, timeout-bounded.",
                    "not_ready plus HTTP 503.",
                    [],
                    "tests/integration/test_health_database_check.py",
                ),
                (
                    "Pack activation status in readiness",
                    "done",
                    "Surface each discovered pack's real catalog.packs state.",
                    "catalog.packs rows.",
                    "ok/degraded with the real reason.",
                    [],
                    "tests/integration/test_health_pack_activation.py",
                ),
                (
                    "Pack health detail with early warning",
                    "done",
                    "Report sub-threshold consecutive failures as degraded before a pack fails.",
                    "catalog.packs.health.",
                    "Degraded status naming the failing agents.",
                    [],
                    "tests/integration/test_health_pack_health_detail.py",
                ),
                (
                    "Continuous pack health polling",
                    "done",
                    "Enforce POLL_INTERVAL_SECONDS with a real background task.",
                    "Discovered packs.",
                    "Repeated polls; task cancelled cleanly on shutdown.",
                    [],
                    "tests/integration/test_health_polling_loop.py",
                ),
                (
                    "Graceful-shutdown coordinator",
                    "todo",
                    "Drain in-flight work before the process exits.",
                    "A shutdown signal.",
                    "No work lost mid-step.",
                    [],
                    "",
                ),
            ],
        },
        5: {
            4: [
                (
                    "OpenTelemetry spans and structlog",
                    "done",
                    "Emit correlated spans and structured logs for every request.",
                    "An HTTP request.",
                    "A span tree plus correlated log lines.",
                    [],
                    "kernel/src/ai_os_kernel/observability",
                ),
                (
                    "First real metric",
                    "done",
                    "Emit at least one genuine platform metric.",
                    "HTTP traffic.",
                    "aios.http.requests.",
                    [],
                    "kernel/src/ai_os_kernel/observability/metrics.py",
                ),
                (
                    "OTLP export to a Collector",
                    "todo",
                    "Export telemetry off-box instead of to the console (ADR-0017).",
                    "Spans and metrics.",
                    "An OTLP endpoint receiving them.",
                    [],
                    "",
                ),
                (
                    "Compose observability profile",
                    "todo",
                    "Stand up Prometheus, Tempo, Loki and Grafana for local use.",
                    "docker-compose profile.",
                    "Dashboards over real telemetry.",
                    [],
                    "",
                ),
                (
                    "Audit log writer with hash chain",
                    "todo",
                    "Write tamper-evident governance.audit_log rows (FR-110).",
                    "A significant action.",
                    "A hash-chained audit row.",
                    [],
                    "",
                ),
                (
                    "Audit chain verification job",
                    "todo",
                    "Detect tampering in the audit chain.",
                    "The audit_log table.",
                    "Pass, or the first broken link.",
                    [],
                    "",
                ),
            ],
        },
        6: {
            42: [
                (
                    "Unit and integration suites",
                    "done",
                    "A real, fast unit suite plus Postgres-backed integration tests.",
                    "pytest with testcontainers.",
                    "1010 passing tests.",
                    [],
                    "tests/",
                ),
                (
                    "Docker-daemon skip guards",
                    "done",
                    "A missing Docker daemon skips container tests cleanly, never crashes.",
                    "An unreachable daemon.",
                    "Clean pytest.skip with a clear reason.",
                    [],
                    "tests/integration/_postgres_fixture.py",
                ),
                (
                    "Coverage gate",
                    "done",
                    "Enforce a real branch-coverage floor in CI.",
                    "pytest-cov over ai_os_kernel.",
                    "Build fails under 90 percent.",
                    [],
                    ".github/workflows/ci.yml",
                ),
                (
                    "tests/security by threat id",
                    "todo",
                    "One passing test per T1-T12 threat control.",
                    "The threat model.",
                    "A test per control.",
                    [],
                    "",
                ),
                (
                    "tests/performance against NFR targets",
                    "todo",
                    "Measure the documented NFR performance targets.",
                    "NFR section 3-5.",
                    "A repeatable performance report.",
                    [],
                    "",
                ),
            ],
            43: [
                (
                    "Lint, types, unit stages",
                    "done",
                    "Run ruff, mypy --strict and the unit suite on every push.",
                    "A pushed commit.",
                    "Three green required stages.",
                    [],
                    ".github/workflows/ci.yml",
                ),
                (
                    "Contract and security stages",
                    "done",
                    "Run the pack contract suite and dependency/secret scans.",
                    "The repository.",
                    "Green contract and security jobs.",
                    [],
                    ".github/workflows/ci.yml",
                ),
                (
                    "Workflow file validity",
                    "done",
                    "The workflow must actually schedule jobs, not fail at parse time.",
                    "ci.yml.",
                    "Real jobs execute; no job-level hashFiles.",
                    [],
                    ".github/workflows/ci.yml",
                ),
                (
                    "Green integration stage on Linux",
                    "todo",
                    "The integration job passes on ubuntu-latest as it does locally.",
                    "tests/unit plus tests/integration.",
                    "A green integration job.",
                    [],
                    "",
                ),
                (
                    "Roadmap generated-doc check in CI",
                    "todo",
                    "Fail the build when a generated roadmap doc is stale or hand-edited.",
                    "Ticket files.",
                    "A CI step running generate --check.",
                    [],
                    "",
                ),
            ],
        },
    },
    2: {
        1: {
            5: [
                (
                    "Definition loading and validation",
                    "done",
                    "Load a declared workflow definition and reject an invalid one.",
                    "A workflow YAML.",
                    "A validated WorkflowDefinition.",
                    [],
                    "kernel/src/ai_os_kernel/workflow_engine/loader.py",
                ),
                (
                    "Instance management and event-sourced state",
                    "done",
                    "Persist instance state as an append-only log plus snapshot, atomically.",
                    "create/start/advance calls.",
                    "workflow_instances plus workflow_events.",
                    [],
                    "kernel/src/ai_os_kernel/workflow_engine/repository.py",
                ),
                (
                    "Sequential agent and tool step execution",
                    "done",
                    "Dispatch each declared step to the agent or tool it names.",
                    "A WorkflowStep.",
                    "Persisted step outputs.",
                    [],
                    "kernel/src/ai_os_kernel/workflow_engine/step_executor.py",
                ),
                (
                    "Lease-based work distribution",
                    "done",
                    "Claim, renew and release an instance lease with SKIP LOCKED.",
                    "A running instance.",
                    "Exclusive, expiring ownership.",
                    [],
                    "kernel/src/ai_os_kernel/workflow_engine/lease.py",
                ),
                (
                    "Continuous lease reaping",
                    "done",
                    "Reclaim a crashed worker's lease without waiting for another acquire.",
                    "Expired leases.",
                    "Reclaimed instances on a real interval.",
                    [],
                    "kernel/src/ai_os_kernel/workflow_engine/lease_reaper.py",
                ),
                (
                    "Failed-attempt recording",
                    "done",
                    "Every failed attempt leaves a real workflow_steps row.",
                    "A raised step exception.",
                    "status=failed row plus step.failed event.",
                    [],
                    "kernel/src/ai_os_kernel/workflow_engine/service.py",
                ),
                (
                    "Bounded step retry, any retriable exception",
                    "done",
                    "Retry any self-declared retriable exception, bounded on attempts and time.",
                    "A retriable exception plus retry_policy.",
                    "Bounded retry, else unchanged FAILED.",
                    [],
                    "kernel/src/ai_os_kernel/workflow_engine/advance_runner.py",
                ),
                (
                    "Registry error retriable classification",
                    "done",
                    "Classify each registry failure cause as retriable or not, explicitly.",
                    "A registry lookup failure.",
                    "retriable set per real cause.",
                    [],
                    "kernel/src/ai_os_kernel/workflow_engine/registry.py",
                ),
                (
                    "decision step type",
                    "todo",
                    "Execute a declared decision step instead of completing as a no-op.",
                    "A decision step.",
                    "A real branch outcome.",
                    [],
                    "",
                ),
                (
                    "parallel step type",
                    "todo",
                    "Execute declared parallel branches concurrently.",
                    "A parallel step.",
                    "Joined branch outputs.",
                    [],
                    "",
                ),
                (
                    "sub_workflow step type",
                    "todo",
                    "Invoke a child workflow and join on its result.",
                    "A sub_workflow step.",
                    "Child outputs in the parent.",
                    [],
                    "",
                ),
                (
                    "Multi-instance worker loop",
                    "todo",
                    "Drive many instances concurrently, not one per call.",
                    "Runnable instances.",
                    "A scheduling loop across instances.",
                    [],
                    "",
                ),
                (
                    "Scheduler for delayed workflow starts",
                    "todo",
                    "Start a workflow on a schedule or after a delay.",
                    "A schedule declaration.",
                    "A started instance at the right time.",
                    [],
                    "",
                ),
            ],
        },
        2: {
            6: [
                (
                    "Anthropic provider adapter",
                    "done",
                    "Route real model calls through one production adapter.",
                    "An LLMRequest.",
                    "A real LLMResponse with usage.",
                    [],
                    "kernel/src/ai_os_kernel/llm_gateway/adapters/anthropic_adapter.py",
                ),
                (
                    "Alias-based routing",
                    "done",
                    "Resolve a model alias to a provider and model id.",
                    "model_alias.",
                    "A RoutingDecision chain.",
                    [],
                    "kernel/src/ai_os_kernel/llm_gateway/router.py",
                ),
                (
                    "Retry, fallback, circuit breaker, backoff",
                    "done",
                    "Survive a failing provider without changing any caller.",
                    "A failing candidate.",
                    "Success on a fallback, with retries recorded.",
                    [],
                    "kernel/src/ai_os_kernel/llm_gateway/gateway.py",
                ),
                (
                    "Error taxonomy and capability matrix",
                    "done",
                    "Classify every provider failure and refuse unsupported capabilities.",
                    "A provider error or capability request.",
                    "category/retriable classification.",
                    [],
                    "kernel/src/ai_os_kernel/llm_gateway/error_taxonomy.py",
                ),
                (
                    "Token and cost accounting",
                    "done",
                    "Record tokens, cost, latency and model identity per call (FR-009).",
                    "A completed call.",
                    "An evaluation.llm_calls row.",
                    [],
                    "kernel/src/ai_os_kernel/llm_gateway/call_recorder.py",
                ),
                (
                    "Second provider adapter",
                    "done",
                    "Prove the Gateway contract with a second real adapter (ADR-0002).",
                    "The same LLMRequest.",
                    "A LocalAdapter response.",
                    [],
                    "kernel/src/ai_os_kernel/llm_gateway/adapters/local_adapter.py",
                ),
                (
                    "Budget enforcement",
                    "partial",
                    "Refuse a call that would exceed a declared budget (FR-022).",
                    "Per-step and per-workflow budgets.",
                    "BudgetExceededError. 2 of 5 checks real.",
                    [],
                    "kernel/src/ai_os_kernel/llm_gateway/budget_enforcer.py",
                ),
                (
                    "Streaming completions",
                    "todo",
                    "Support stream() for long outputs.",
                    "An LLMRequest.",
                    "A token stream.",
                    [],
                    "",
                ),
                (
                    "Embeddings",
                    "todo",
                    "Support embed() for retrieval.",
                    "Text.",
                    "Vectors.",
                    [],
                    "",
                ),
                (
                    "Provider token counting",
                    "todo",
                    "Support count_tokens() against the provider endpoint.",
                    "A prompt.",
                    "An exact token count.",
                    [],
                    "",
                ),
                (
                    "Rate limiter",
                    "todo",
                    "Respect per-provider rate limits proactively.",
                    "Request volume.",
                    "Throttled dispatch.",
                    [],
                    "",
                ),
                (
                    "Prompt-cache planner",
                    "todo",
                    "Plan cache boundaries to reduce cost.",
                    "An assembled prompt.",
                    "Cache-annotated request.",
                    [],
                    "",
                ),
            ],
        },
        3: {
            7: [
                (
                    "In-memory prompt engine",
                    "done",
                    "Render a versioned template with validated variables.",
                    "prompt_id, version, variables.",
                    "A rendered prompt.",
                    [],
                    "kernel/src/ai_os_kernel/prompt_engine/renderer.py",
                ),
                (
                    "SQL prompt catalog",
                    "done",
                    "Resolve prompts from catalog.prompts with content hashing.",
                    "prompt_id plus version.",
                    "Template content plus hash.",
                    [],
                    "kernel/src/ai_os_kernel/prompt_engine/catalog.py",
                ),
                (
                    "Missing-variable rejection",
                    "done",
                    "Fail before the model call when a required variable is absent (FR-011).",
                    "Incomplete variables.",
                    "A clear pre-call error.",
                    [],
                    "kernel/src/ai_os_kernel/prompt_engine/renderer.py",
                ),
                (
                    "Prompt resolver by role or alias",
                    "todo",
                    "Resolve a prompt without a caller hardcoding its id.",
                    "A role or alias.",
                    "The resolved prompt.",
                    [],
                    "",
                ),
                (
                    "Composition and inheritance",
                    "todo",
                    "Build a prompt from reusable fragments.",
                    "Fragments.",
                    "One composed prompt.",
                    [],
                    "",
                ),
                (
                    "Cache boundary index",
                    "todo",
                    "Mark where a provider prompt cache should split.",
                    "A template.",
                    "Boundary annotations.",
                    [],
                    "",
                ),
            ],
            8: [
                (
                    "Deterministic, budget-bounded assembly",
                    "done",
                    "Assemble identical context for identical inputs, within budget (FR-010).",
                    "A ContextRequest.",
                    "A deterministic AssembledContext.",
                    [],
                    "kernel/src/ai_os_kernel/context_manager/manager.py",
                ),
                (
                    "Workflow-state resolver",
                    "done",
                    "Expose the running instance's own state to a step.",
                    "workflow_id.",
                    "Instance state context items.",
                    [],
                    "kernel/src/ai_os_kernel/context_manager/resolvers.py",
                ),
                (
                    "Step-output resolver with transforms",
                    "done",
                    "Feed a prior step's real persisted output into a later step.",
                    "step_sources mapping.",
                    "Field-selected, transformed context.",
                    [],
                    "kernel/src/ai_os_kernel/context_manager/resolvers.py",
                ),
                (
                    "Trust tagging on every item",
                    "done",
                    "Every context item carries provenance and a trust level.",
                    "A resolved item.",
                    "SourceRef plus trust.",
                    [],
                    "kernel/src/ai_os_kernel/context_manager/models.py",
                ),
                (
                    "Knowledge resolver",
                    "todo",
                    "Bring knowledge-base content into step context.",
                    "A query.",
                    "Ranked knowledge items.",
                    [],
                    "",
                ),
                (
                    "Memory resolver",
                    "todo",
                    "Bring durable memory into context.",
                    "A scope.",
                    "Memory items.",
                    [],
                    "",
                ),
                (
                    "AI-context-pack resolver",
                    "todo",
                    "Load declared AI context packs.",
                    "A pack reference.",
                    "Context items.",
                    [],
                    "",
                ),
                (
                    "Runtime-config resolver",
                    "todo",
                    "Expose runtime configuration as context.",
                    "Config keys.",
                    "Context items.",
                    [],
                    "",
                ),
                (
                    "Filter and ranker",
                    "todo",
                    "Rank and trim candidates to fit the budget by relevance, not order.",
                    "Candidate items.",
                    "A ranked, trimmed set.",
                    [],
                    "",
                ),
                (
                    "Persisted context audit logger",
                    "todo",
                    "Record exactly what context each step actually received.",
                    "An assembled context.",
                    "A durable audit row.",
                    [],
                    "",
                ),
            ],
        },
        4: {
            9: [
                (
                    "Knowledge writer",
                    "done",
                    "Persist knowledge documents and chunks.",
                    "Chunked input.",
                    "knowledge.documents plus chunks.",
                    [],
                    "kernel/src/ai_os_kernel/persistence/knowledge_writer.py",
                ),
                (
                    "Keyword search reader",
                    "done",
                    "Retrieve knowledge by full-text search.",
                    "A query string.",
                    "Ranked matches.",
                    [],
                    "kernel/src/ai_os_kernel/persistence/knowledge_keyword_search.py",
                ),
                (
                    "Indexing component",
                    "todo",
                    "Maintain the retrievable index as content changes.",
                    "New or changed documents.",
                    "An updated index.",
                    [],
                    "",
                ),
                (
                    "Query engine",
                    "todo",
                    "Answer knowledge queries behind one interface.",
                    "A query.",
                    "Ranked results with provenance.",
                    [],
                    "",
                ),
                (
                    "Provenance and versioning",
                    "todo",
                    "Every retrieved item carries source and version (FR-112).",
                    "A retrieved item.",
                    "Source plus version.",
                    [],
                    "",
                ),
            ],
            10: [
                (
                    "Memory store",
                    "todo",
                    "Durable store for cross-run memory.",
                    "Memory writes.",
                    "A queryable store.",
                    [],
                    "",
                ),
                (
                    "Memory writer",
                    "todo",
                    "Record memory items with scope and provenance.",
                    "A memory item.",
                    "A persisted row.",
                    [],
                    "",
                ),
                (
                    "Promotion logic",
                    "todo",
                    "Promote recurring context into durable memory.",
                    "Observed repetition.",
                    "A promoted memory item.",
                    [],
                    "",
                ),
            ],
            11: [
                (
                    "Keyword full-text search",
                    "done",
                    "Real FTS over stored chunks.",
                    "A query.",
                    "Ranked chunk matches.",
                    [],
                    "kernel/src/ai_os_kernel/persistence/knowledge_keyword_search.py",
                ),
                (
                    "pgvector schema",
                    "done",
                    "Vector columns and indexes exist (ADR-0013).",
                    "Migrations.",
                    "A pgvector-ready schema.",
                    [],
                    "kernel/alembic/versions",
                ),
                (
                    "Embedding writer",
                    "todo",
                    "Populate vectors for stored chunks.",
                    "Chunk text.",
                    "Stored embeddings.",
                    [],
                    "",
                ),
                (
                    "Vector search",
                    "todo",
                    "Nearest-neighbour retrieval over embeddings.",
                    "A query vector.",
                    "Ranked neighbours.",
                    [],
                    "",
                ),
                (
                    "Hybrid RRF fusion",
                    "todo",
                    "Fuse keyword and vector results (ADR-0013).",
                    "Two ranked lists.",
                    "One fused ranking.",
                    [],
                    "",
                ),
                (
                    "Retrieval service",
                    "todo",
                    "One service interface over both strategies.",
                    "A retrieval request.",
                    "Ranked results.",
                    [],
                    "",
                ),
            ],
        },
        5: {
            13: [
                (
                    "Register, activate, deactivate",
                    "done",
                    "Move a pack through the canonical lifecycle without a restart.",
                    "A pack manifest.",
                    "catalog.packs state transitions.",
                    [],
                    "kernel/src/ai_os_kernel/capability_manager/repository.py",
                ),
                (
                    "Transition audit trail",
                    "done",
                    "Every transition is recorded.",
                    "A transition.",
                    "A catalog.pack_state_transitions row.",
                    [],
                    "kernel/src/ai_os_kernel/capability_manager/repository.py",
                ),
                (
                    "mark_failed transition",
                    "done",
                    "Move a persistently unhealthy pack to failed.",
                    "Consecutive health failures.",
                    "state=failed, audited.",
                    [],
                    "kernel/src/ai_os_kernel/capability_manager/repository.py",
                ),
                (
                    "Manifest to catalog installer",
                    "done",
                    "Derive catalog.agents/prompts/tools rows from a real manifest.",
                    "A pack root.",
                    "Real catalog rows in one transaction.",
                    [],
                    "kernel/src/ai_os_kernel/capability_manager/manifest_catalog_installer.py",
                ),
                (
                    "Startup pack discovery and activation",
                    "done",
                    "A fresh Kernel registers and activates discovered packs unattended.",
                    "capability_pack_dirs.",
                    "Activated packs, idempotent across restarts.",
                    [],
                    "tests/integration/test_bootstrap_pack_discovery.py",
                ),
                (
                    "Pack health polling",
                    "done",
                    "Resolve each pack's agents on an interval and record health.",
                    "Activated packs.",
                    "catalog.packs.health snapshots.",
                    [],
                    "kernel/src/ai_os_kernel/capability_manager/health_poller.py",
                ),
                (
                    "Pack upgrade path",
                    "todo",
                    "Upgrade an activated pack to a new version safely.",
                    "A newer pack version.",
                    "A migrated, activated pack.",
                    [],
                    "",
                ),
                (
                    "Permissions enforcement at resolution",
                    "todo",
                    "Refuse to resolve an agent whose permissions exceed its pack grant.",
                    "An agent row.",
                    "Refusal on over-grant.",
                    [],
                    "",
                ),
            ],
            18: [
                (
                    "ToolInvoker Protocol in the SDK",
                    "done",
                    "A backend-agnostic tool invocation contract packs can depend on.",
                    "A tool id plus arguments.",
                    "A ToolResult.",
                    [],
                    "platform_sdk/src/ai_os_sdk/contracts",
                ),
                (
                    "Kernel ToolInvokerAdapter",
                    "done",
                    "Implement the Protocol over the real sandbox.",
                    "A tool invocation.",
                    "Real sandboxed execution.",
                    [],
                    "kernel/src/ai_os_kernel/sdk_adapters",
                ),
                (
                    "Manifest-declared tool resolution",
                    "todo",
                    "Resolve a pack-declared Tool through the registry, not an internal shim.",
                    "A declared toolId.",
                    "A resolved, trust-tiered Tool.",
                    [],
                    "",
                ),
            ],
            27: [
                (
                    "Packaging scaffold",
                    "done",
                    "A real installable ai-os-sdk distribution.",
                    "pyproject.",
                    "A buildable wheel.",
                    [],
                    "platform_sdk/pyproject.toml",
                ),
                (
                    "Error taxonomy and boundary models",
                    "done",
                    "Shared error and data shapes at the pack boundary.",
                    "n/a.",
                    "ai_os_sdk.errors plus models.",
                    [],
                    "platform_sdk/src/ai_os_sdk/models",
                ),
                (
                    "Agent and Tool Protocols",
                    "done",
                    "Structural contracts every real agent and tool satisfies unmodified.",
                    "Existing agents and tools.",
                    "Protocol conformance.",
                    [],
                    "platform_sdk/src/ai_os_sdk/contracts",
                ),
                (
                    "LLMGateway, PromptRegistry, ToolInvoker Protocols",
                    "done",
                    "The three capability contracts a pack may be granted.",
                    "Kernel implementations.",
                    "Protocols satisfied by real objects.",
                    [],
                    "platform_sdk/src/ai_os_sdk/contracts",
                ),
                (
                    "Kernel-side adapters",
                    "done",
                    "Real adapters implementing each SDK Protocol over Kernel internals.",
                    "Kernel objects.",
                    "SDK-shaped capabilities.",
                    [],
                    "kernel/src/ai_os_kernel/sdk_adapters",
                ),
                (
                    "PackContextReceiver injection",
                    "done",
                    "Inject a permission-gated PackContext into a zero-arg entrypoint.",
                    "A resolved entrypoint.",
                    "bind_pack_context called with real capabilities.",
                    [],
                    "kernel/src/ai_os_kernel/workflow_engine/registry.py",
                ),
                (
                    "Pack contract suite, 9 checks",
                    "done",
                    "Automated proof a pack satisfies the published contract.",
                    "A pack root.",
                    "9 checks, zero waivers.",
                    [],
                    "platform_sdk/src/ai_os_sdk/testing/pack_contract_suite.py",
                ),
                (
                    "Six module migrations off Kernel imports",
                    "done",
                    "The Software Engineering pack imports no Kernel internals.",
                    "Pack modules.",
                    "Zero ai_os_kernel imports, enforced in CI.",
                    [],
                    "scripts/check_import_boundaries.py",
                ),
            ],
        },
        6: {
            15: [
                (
                    "Blocking quality_gate step executor",
                    "done",
                    "A failing blocking gate halts the workflow (FR-012, ADR-0006).",
                    "A configured source step output.",
                    "QualityGateFailedError on non-pass.",
                    [],
                    "kernel/src/ai_os_kernel/workflow_engine/quality_gate.py",
                ),
                (
                    "Second gate category via configuration",
                    "done",
                    "Prove the mechanism generalises with a static-analysis gate.",
                    "A lint step output.",
                    "A second real blocking gate.",
                    [],
                    "kernel/src/ai_os_kernel/workflow_engine/delivery_pipeline.py",
                ),
                (
                    "Bounded gate retry",
                    "done",
                    "Retry a failed gate from a configured earlier step, bounded.",
                    "retryPolicy plus a retry target.",
                    "Bounded re-execution.",
                    [],
                    "kernel/src/ai_os_kernel/workflow_engine/advance_runner.py",
                ),
                (
                    "evaluation.gate_results writer",
                    "done",
                    "Record every gate resolution, pass or fail.",
                    "A resolved gate step row.",
                    "A real evaluation.gate_results row.",
                    [],
                    "kernel/src/ai_os_kernel/workflow_engine/gate_result_recorder.py",
                ),
                (
                    "Gate Registry",
                    "todo",
                    "Resolve a declared gate id to a real gate definition.",
                    "A gateId.",
                    "A resolved gate.",
                    [],
                    "",
                ),
                (
                    "Pack-declared gate definitions",
                    "todo",
                    "Let a pack contribute gates with evaluationMethod and successCriteria.",
                    "A manifest gate declaration.",
                    "A registered, runnable gate.",
                    [],
                    "",
                ),
                (
                    "Result Evaluator and Policy Enforcer",
                    "todo",
                    "Separate evaluating a result from enforcing blocking vs warning severity.",
                    "A gate result.",
                    "A policy decision.",
                    [],
                    "",
                ),
                (
                    "Parallel gate execution",
                    "todo",
                    "Run independent gates concurrently when safe.",
                    "Several gates.",
                    "Joined results.",
                    [],
                    "",
                ),
            ],
        },
        7: {
            17: [
                (
                    "event_outbox table",
                    "done",
                    "Transactional outbox schema exists (ADR-0012).",
                    "Migrations.",
                    "platform.event_outbox.",
                    [],
                    "kernel/alembic/versions",
                ),
                (
                    "In-process asyncio event bus",
                    "todo",
                    "Publish and subscribe in-process.",
                    "An event.",
                    "Delivered to subscribers.",
                    [],
                    "",
                ),
                (
                    "Outbox relay",
                    "todo",
                    "Drain the outbox at least once (FR-014).",
                    "Outbox rows.",
                    "Published events with correlation ids.",
                    [],
                    "",
                ),
            ],
            21: [
                (
                    "Content-addressed artifact store",
                    "todo",
                    "Store workflow artifacts by content hash instead of temp directories.",
                    "An artifact.",
                    "An addressable, retrievable object.",
                    [],
                    "",
                ),
            ],
            23: [
                (
                    "Redis client integration",
                    "todo",
                    "Actually use the Redis that Compose already provisions.",
                    "Config.",
                    "A working client.",
                    [],
                    "",
                ),
                (
                    "Response cache",
                    "todo",
                    "Cache responses, disabled for experiments (ADR-0025).",
                    "A cacheable call.",
                    "A cache hit or miss, recorded.",
                    [],
                    "",
                ),
            ],
            44: [
                (
                    "Platform-wide AiOsError hierarchy",
                    "todo",
                    "One shared error base with structured codes (error_handling_retry.md §8).",
                    "Existing local error classes.",
                    "A shared hierarchy plus StructuredError.",
                    [],
                    "",
                ),
            ],
        },
        8: {
            36: [
                (
                    "Health routes",
                    "done",
                    "Expose liveness and readiness over HTTP.",
                    "An HTTP GET.",
                    "/health/live, /health/ready.",
                    [],
                    "kernel/src/ai_os_kernel/routes/health.py",
                ),
                (
                    "Workflow routes",
                    "done",
                    "Start and inspect workflows over HTTP.",
                    "An authenticated request.",
                    "Workflow create/list/detail.",
                    [],
                    "kernel/src/ai_os_kernel/routes/workflows.py",
                ),
                (
                    "Pack routes",
                    "done",
                    "Register, activate and list packs over HTTP.",
                    "An authenticated request.",
                    "Pack lifecycle endpoints.",
                    [],
                    "kernel/src/ai_os_kernel/routes/packs.py",
                ),
                (
                    "Delivery pipeline route",
                    "done",
                    "Trigger the real Software Engineering pipeline over HTTP.",
                    "A requirement string.",
                    "A run result with documentation_path.",
                    [],
                    "kernel/src/ai_os_kernel/routes/delivery_pipeline.py",
                ),
            ],
        },
    },
    3: {
        1: {
            20: [
                (
                    "LocalSubprocessSandbox",
                    "done",
                    "Run a command in a bounded subprocess.",
                    "A command.",
                    "Captured output with limits.",
                    [],
                    "kernel/src/ai_os_kernel/sandbox/executor.py",
                ),
                (
                    "DockerSandbox as the default backend",
                    "done",
                    "Run untrusted generated code in an ephemeral container (ADR-0016).",
                    "A command.",
                    "Container-isolated execution.",
                    [],
                    "kernel/src/ai_os_kernel/sandbox/docker_executor.py",
                ),
                (
                    "Live-verified network isolation",
                    "done",
                    "Prove a Tier 1 step genuinely has no network (FR-021).",
                    "Generated code attempting egress.",
                    "A live-verified failure to reach the network.",
                    [],
                    "tests/integration/sandbox/test_docker_sandbox_live.py",
                ),
                (
                    "Live-verified filesystem containment",
                    "done",
                    "Prove a Tier 1 step cannot reach the host filesystem.",
                    "Generated code attempting host access.",
                    "Verified containment.",
                    [],
                    "tests/integration/sandbox/test_docker_sandbox_live.py",
                ),
                (
                    "Stronger isolation tier",
                    "todo",
                    "Offer a gVisor or Firecracker backed tier for higher-risk work.",
                    "A trust tier request.",
                    "A stronger sandbox.",
                    [],
                    "",
                ),
            ],
            24: [
                # R-001 (hard product-owner rule, 2026-07-31): no deploy or
                # publish capability ships before the approval guardrail.
                (
                    "Git integration service",
                    "todo",
                    "Commit, branch and push generated work under policy.",
                    "A workspace.",
                    "Real Git operations, audited.",
                    ["P03-S05-M14-T04", "P03-S05-M14-T05"],
                    "",
                ),
            ],
        },
        2: {
            29: [
                (
                    "requirements-analyst agent",
                    "done",
                    "Refine a raw ask into structured requirements.",
                    "A requirement string.",
                    "A validated analysis output.",
                    [],
                    "capability_packs/software-engineering/src/ai_os_pack_software_engineering/agents/requirements_analyst.py",
                ),
                (
                    "architecture agent",
                    "done",
                    "Produce a solution design from requirements.",
                    "Analysed requirements.",
                    "A design artifact.",
                    [],
                    "capability_packs/software-engineering/src/ai_os_pack_software_engineering/agents/architecture.py",
                ),
                (
                    "build agent",
                    "done",
                    "Write real source files from a design.",
                    "A design.",
                    "A file written through the sandbox.",
                    [],
                    "capability_packs/software-engineering/src/ai_os_pack_software_engineering/agents/build.py",
                ),
                (
                    "qa-test agent",
                    "done",
                    "Execute the generated artifact and report pass or fail.",
                    "A generated file.",
                    "passed, exitCode, output.",
                    [],
                    "capability_packs/software-engineering/src/ai_os_pack_software_engineering/agents/verification.py",
                ),
                (
                    "documentation agent",
                    "done",
                    "Record a documentation artifact for the build.",
                    "Build and test outputs.",
                    "A written documentation file.",
                    [],
                    "capability_packs/software-engineering/src/ai_os_pack_software_engineering/agents/documentation.py",
                ),
                (
                    "lint agent",
                    "done",
                    "Run a real static-analysis check on generated code.",
                    "A generated file.",
                    "passed, exitCode, output.",
                    [],
                    "capability_packs/software-engineering/src/ai_os_pack_software_engineering/agents/lint.py",
                ),
                (
                    "code-reviewer agent",
                    "todo",
                    "Produce structured review findings with file, line, severity (FR-039).",
                    "Generated code.",
                    "Structured findings.",
                    [],
                    "",
                ),
                (
                    "technical-planner agent",
                    "todo",
                    "Decompose an architecture into an executable plan (FR-033).",
                    "A design.",
                    "A plan artifact driving a foreach step.",
                    [],
                    "",
                ),
            ],
        },
        3: {
            30: [
                (
                    "se.delivery_pipeline",
                    "done",
                    "Chain six agents plus two blocking gates end to end.",
                    "A requirement.",
                    "A completed run with a documentation artifact.",
                    [],
                    "capability_packs/software-engineering/workflows/delivery_pipeline.yaml",
                ),
                (
                    "Structured Markdown specification input",
                    "todo",
                    "Accept a structured Markdown spec, not a raw string (FR-030).",
                    "A Markdown specification.",
                    "Parsed, validated requirement items.",
                    [],
                    "",
                ),
                (
                    "Bounded review-revise loop",
                    "todo",
                    "Iterate implementation until a gate passes or a bound is hit (FR-045).",
                    "Review findings.",
                    "A terminating loop.",
                    [],
                    "",
                ),
            ],
        },
        4: {
            31: [
                (
                    "Internal sandboxed command tool",
                    "done",
                    "A working sandbox-backed command tool used by real agents.",
                    "A command.",
                    "Sandboxed execution.",
                    [],
                    "kernel/src/ai_os_kernel/workflow_engine/sandboxed_tool.py",
                ),
                (
                    "Manifest-declared file and build tools",
                    "todo",
                    "Declare real, trust-tiered tools in the pack manifest.",
                    "Tool declarations.",
                    "Registry-resolvable Tools.",
                    [],
                    "",
                ),
                (
                    "Pack-declared gate definitions",
                    "todo",
                    "Move the pipeline's gates into pack-declared definitions.",
                    "Manifest gate entries.",
                    "Registered gates.",
                    [],
                    "",
                ),
            ],
        },
        5: {
            14: [
                (
                    "Bearer-token authentication",
                    "done",
                    "Authenticate API callers with a signed token.",
                    "An Authorization header.",
                    "An authenticated principal.",
                    [],
                    "kernel/src/ai_os_kernel/security_manager",
                ),
                (
                    "Route permission checks",
                    "done",
                    "Refuse a request lacking the route's declared permission.",
                    "A principal plus route.",
                    "403 on missing permission.",
                    [],
                    "kernel/src/ai_os_kernel/security_manager",
                ),
                (
                    "Monotonic permission narrowing",
                    "todo",
                    "A tool cannot exercise a permission its agent or workflow lacks (FR-018).",
                    "The principal-workflow-agent-tool chain.",
                    "Enforced narrowing at each hop.",
                    [],
                    "",
                ),
                (
                    "Human Approval Manager",
                    "todo",
                    "Pause at an approval point; resume only on an authorized decision (FR-013).",
                    "A human_approval step.",
                    "waiting_for_human; never approves on timeout.",
                    [],
                    "",
                ),
                (
                    "governance.approvals writer",
                    "todo",
                    "Persist approval requests and decisions (FR-111).",
                    "An approval decision.",
                    "A durable approvals row.",
                    [],
                    "",
                ),
            ],
        },
        6: {
            41: [
                (
                    "T1 generated-code containment",
                    "done",
                    "Prove generated code cannot escape the sandbox.",
                    "Hostile generated code.",
                    "A live-verified containment test.",
                    [],
                    "tests/integration/sandbox/test_docker_sandbox_live.py",
                ),
                (
                    "Remaining T2-T12 controls",
                    "todo",
                    "One passing test per remaining threat control.",
                    "The threat model.",
                    "A test per control under tests/security.",
                    [],
                    "",
                ),
            ],
        },
    },
    4: {
        1: {
            12: [
                (
                    "Six evaluation tables",
                    "done",
                    "Schema for the full evaluation domain.",
                    "Migrations.",
                    "run_manifests, experiments, experiment_runs, metrics, gate_results.",
                    [],
                    "kernel/src/ai_os_kernel/persistence/evaluation_schema.py",
                ),
                (
                    "gate_results writer",
                    "done",
                    "First real producer of evaluation data.",
                    "A resolved gate.",
                    "A real gate_results row.",
                    [],
                    "kernel/src/ai_os_kernel/workflow_engine/gate_result_recorder.py",
                ),
                (
                    "llm_calls writer",
                    "done",
                    "Record model spend per call.",
                    "A completed LLM call.",
                    "An evaluation.llm_calls row.",
                    [],
                    "kernel/src/ai_os_kernel/llm_gateway/call_recorder.py",
                ),
                (
                    "Metrics collector",
                    "todo",
                    "Collect quality, cost, performance and process metrics per run (FR-073).",
                    "A completed run.",
                    "evaluation.metrics rows.",
                    [],
                    "",
                ),
                (
                    "Run manifest recorder",
                    "todo",
                    "Record a complete, re-launchable run manifest (FR-020, ADR-0022).",
                    "A workflow run.",
                    "A schema-valid manifest.",
                    [],
                    "",
                ),
                (
                    "Comparison computer with variance",
                    "todo",
                    "Report mean and variance across replicates, not point values (FR-074).",
                    "Replicate metrics.",
                    "A comparison with variance.",
                    [],
                    "",
                ),
                (
                    "Cache-served exclusion",
                    "todo",
                    "Exclude and flag cache-served runs from aggregates (FR-075).",
                    "Runs with served_from_cache.",
                    "Excluded, flagged aggregates.",
                    [],
                    "",
                ),
                (
                    "Reporting interface",
                    "todo",
                    "Expose comparison results for consumption.",
                    "Computed comparisons.",
                    "A queryable report.",
                    [],
                    "",
                ),
            ],
        },
        2: {
            16: [
                (
                    "trace.links writer",
                    "todo",
                    "Record requirement to architecture to module to test links (FR-019).",
                    "Traceable artifacts.",
                    "trace.links rows.",
                    [],
                    "",
                ),
                (
                    "Impact query",
                    "todo",
                    "Answer what is affected by changing module X.",
                    "A module id.",
                    "Affected artifacts.",
                    [],
                    "",
                ),
                (
                    "Coverage query",
                    "todo",
                    "Report requirements lacking a verifying test (FR-115).",
                    "trace.links.",
                    "Uncovered requirement ids.",
                    [],
                    "",
                ),
            ],
        },
        3: {
            34: [
                (
                    "Experiment definition with pinned conditions",
                    "todo",
                    "Define an experiment pinning workflow, prompts, tools and config (FR-070).",
                    "An experiment spec.",
                    "A validated definition.",
                    [],
                    "",
                ),
                (
                    "Replicate management",
                    "todo",
                    "Run at least 3 replicates per variant (FR-072).",
                    "A variant.",
                    "Recorded replicates.",
                    [],
                    "",
                ),
                (
                    "Cost ceiling enforcement",
                    "todo",
                    "Refuse an experiment projected over its ceiling before any call (FR-076).",
                    "A projected cost.",
                    "Refusal before dispatch.",
                    [],
                    "",
                ),
                (
                    "Prompt adaptation recording",
                    "todo",
                    "Record any per-model prompt adaptation as a declared variable (FR-077).",
                    "An adapted prompt.",
                    "A recorded experiment variable.",
                    [],
                    "",
                ),
            ],
        },
    },
    5: {
        1: {
            26: [
                (
                    "Parser adapters",
                    "todo",
                    "Parse real document formats into text.",
                    "A document.",
                    "Extracted text plus metadata.",
                    [],
                    "",
                ),
                (
                    "Chunking pipeline",
                    "todo",
                    "Chunk extracted text for the knowledge writer.",
                    "Extracted text.",
                    "Chunks ready to index.",
                    [],
                    "",
                ),
            ],
        },
        2: {
            32: [
                (
                    "Repository ingestion and structural model",
                    "todo",
                    "Ingest a repository and build a module and file inventory (FR-050).",
                    "A repository.",
                    "A structural model.",
                    [],
                    "",
                ),
                (
                    "Language and framework detection",
                    "todo",
                    "Detect languages, frameworks and build systems with confidence (FR-051).",
                    "A repository.",
                    "A detection report.",
                    [],
                    "",
                ),
                (
                    "Dependency graph",
                    "todo",
                    "Construct queryable module and dependency graphs (FR-052).",
                    "A structural model.",
                    "A graph artifact.",
                    [],
                    "",
                ),
                (
                    "Architecture recovery",
                    "todo",
                    "Recover architectural boundaries and document them (FR-053).",
                    "A dependency graph.",
                    "An architecture artifact.",
                    [],
                    "",
                ),
                (
                    "Documentation generation",
                    "todo",
                    "Generate documentation for a poorly documented system (FR-056).",
                    "A recovered model.",
                    "A documentation set.",
                    [],
                    "",
                ),
                (
                    "Untrusted provenance end to end",
                    "todo",
                    "Tag every derived item untrusted through the whole pipeline (FR-059).",
                    "Ingested content.",
                    "trust=untrusted on every derived item.",
                    [],
                    "",
                ),
            ],
        },
    },
    6: {
        1: {
            36: [
                (
                    "Published OpenAPI contract artifact",
                    "todo",
                    "Export the OpenAPI 3.1 document to a committed file (ADR-0018).",
                    "The FastAPI app.",
                    "A committed openapi.json plus a drift check.",
                    [],
                    "",
                ),
                (
                    "RFC 9457 error shape",
                    "todo",
                    "Return problem+json errors consistently.",
                    "Any error.",
                    "An RFC 9457 body.",
                    [],
                    "",
                ),
                (
                    "Idempotency-Key support",
                    "todo",
                    "Make unsafe requests safely retryable.",
                    "An Idempotency-Key header.",
                    "At-most-once effect.",
                    [],
                    "",
                ),
                (
                    "Remaining documented routes",
                    "todo",
                    "Implement the rest of the ~45 documented endpoints.",
                    "api_architecture.md.",
                    "Implemented, tested routes.",
                    [],
                    "",
                ),
            ],
        },
        2: {
            37: [
                (
                    "WebSocket stream endpoint",
                    "todo",
                    "Stream live workflow updates without a page reload (FR-096, ADR-0014).",
                    "A subscription.",
                    "Live events over /api/v1/stream.",
                    [],
                    "",
                ),
            ],
        },
        3: {
            39: [
                (
                    "Dashboard scaffold on the generated client",
                    "todo",
                    "Stand up React/TS/Vite consuming only the generated API client (ADR-0018).",
                    "The published OpenAPI contract.",
                    "A running dashboard shell.",
                    [],
                    "",
                ),
                (
                    "Overview, workflows and approvals views",
                    "todo",
                    "Render health, workflow detail and pending approvals (FR-090 to FR-092).",
                    "API data.",
                    "Working views with drill-down.",
                    [],
                    "",
                ),
                (
                    "Cost and quality views",
                    "todo",
                    "Show cost breakdown and gate trends (FR-094, FR-095).",
                    "Evaluation data.",
                    "Reconciling breakdowns.",
                    [],
                    "",
                ),
            ],
        },
        4: {
            38: [
                (
                    "aios CLI",
                    "todo",
                    "Scriptable workflows, approvals, experiments and health (FR-098).",
                    "CLI arguments.",
                    "Machine-readable output plus exit codes.",
                    [],
                    "",
                ),
            ],
        },
        5: {
            22: [
                (
                    "Notification channels",
                    "todo",
                    "Deliver approval, failure and completion notices (FR-116).",
                    "A platform event.",
                    "A delivered notification.",
                    [],
                    "",
                ),
                (
                    "Delivery status recording",
                    "todo",
                    "Record whether delivery succeeded.",
                    "A send attempt.",
                    "A recorded status.",
                    [],
                    "",
                ),
            ],
        },
        6: {
            25: [
                (
                    "Speech Gateway",
                    "todo",
                    "Wake word, intent recognition, spoken response (ADR-0019).",
                    "Audio input.",
                    "Recognised intent plus spoken output.",
                    [],
                    "",
                ),
            ],
            33: [
                (
                    "Voice pack MVP",
                    "todo",
                    "Status, control and approvals by voice (FR-099).",
                    "A voice intent.",
                    "A platform action.",
                    [],
                    "",
                ),
            ],
        },
    },
    7: {
        1: {
            40: [
                # R-001 (hard product-owner rule, 2026-07-31): deployment
                # capability is blocked on the Human Approval guardrail.
                (
                    "Kubernetes manifests and Helm chart",
                    "todo",
                    "Deploy the platform with the supported sandbox patterns (ADR-0020).",
                    "A built image.",
                    "Applied manifests.",
                    ["P03-S05-M14-T04", "P03-S05-M14-T05"],
                    "",
                ),
                (
                    "NetworkPolicy egress allowlist",
                    "todo",
                    "Restrict egress to declared destinations.",
                    "Cluster policy.",
                    "Enforced allowlist.",
                    [],
                    "",
                ),
                (
                    "Backup and restore rehearsal",
                    "todo",
                    "Prove a restore works including audit-chain verification.",
                    "A backup.",
                    "A verified restore.",
                    [],
                    "",
                ),
            ],
        },
        2: {
            14: [
                (
                    "OIDC authentication",
                    "todo",
                    "Replace the pre-shared JWT with real OIDC (ADR-0023).",
                    "An OIDC provider.",
                    "Federated authentication.",
                    [],
                    "",
                ),
                (
                    "Full five-role model",
                    "todo",
                    "Implement every documented role.",
                    "Role definitions.",
                    "Enforced role-based access.",
                    [],
                    "",
                ),
            ],
            19: [
                (
                    "Vault secrets backend",
                    "todo",
                    "Resolve secrets from Vault (ADR-0024).",
                    "A Vault reference.",
                    "A resolved secret.",
                    [],
                    "",
                ),
            ],
        },
        3: {
            42: [
                (
                    "Chaos tests",
                    "todo",
                    "Kill worker, kill Redis, drop provider.",
                    "A running system.",
                    "Proven recovery.",
                    [],
                    "",
                ),
                (
                    "Cost anomaly alerting",
                    "todo",
                    "Alert on abnormal spend.",
                    "Cost telemetry.",
                    "An alert.",
                    [],
                    "",
                ),
            ],
        },
    },
    8: {
        1: {
            29: [
                (
                    "frontend-developer agent",
                    "todo",
                    "Implement frontend components (FR-035).",
                    "A plan.",
                    "Generated frontend code.",
                    [],
                    "",
                ),
                (
                    "database agent",
                    "todo",
                    "Design schemas and reversible migrations (FR-036).",
                    "A design.",
                    "A migration.",
                    [],
                    "",
                ),
                (
                    "api-designer agent",
                    "todo",
                    "Define versioned API contracts (FR-037).",
                    "A design.",
                    "A contract artifact.",
                    [],
                    "",
                ),
                (
                    "security-analysis agent",
                    "todo",
                    "Analyse generated code for vulnerabilities (FR-040).",
                    "Generated code.",
                    "Security findings.",
                    [],
                    "",
                ),
                (
                    "release agent",
                    "todo",
                    "Manage version, changelog and readiness (FR-042).",
                    "A build.",
                    "A release readiness result.",
                    [],
                    "",
                ),
                (
                    "refactoring agent",
                    "todo",
                    "Refactor without changing behaviour (FR-043).",
                    "Existing code.",
                    "Refactored code, tests unchanged.",
                    [],
                    "",
                ),
                (
                    "performance agent",
                    "todo",
                    "Recommend optimisations (FR-044, post-v1).",
                    "A running system.",
                    "A performance report.",
                    [],
                    "",
                ),
            ],
        },
        2: {
            30: [
                (
                    "se.product_creation workflow",
                    "todo",
                    "The full documented product-creation workflow.",
                    "A specification.",
                    "A completed multi-stage run.",
                    [],
                    "",
                ),
                (
                    "se.implement_task workflow",
                    "todo",
                    "The narrower single-task implementation workflow.",
                    "A task.",
                    "A completed run.",
                    [],
                    "",
                ),
            ],
        },
    },
}

TEMPLATE = """---
id: {tid}
title: {title}
status: {status}
depends_on: [{deps}]
evidence: [{evidence}]
module_path: {module_path}
---
**Goal:** {goal}
**Input:** {inp}
**Output:** {outp}
"""


def build() -> list[tuple[Path, str]]:
    out: list[tuple[Path, str]] = []
    for phase, stages in SEED.items():
        for stage, modules in stages.items():
            for module, tasks in modules.items():
                for i, (title, status, goal, inp, outp, deps, evidence) in enumerate(tasks, 1):
                    tid = f"P{phase:02d}-S{stage:02d}-M{module:02d}-T{i:02d}"
                    path = TICKETS_ROOT / f"P{phase:02d}" / f"{tid}.md"
                    out.append(
                        (
                            path,
                            TEMPLATE.format(
                                tid=tid,
                                title=title,
                                status=status,
                                deps=", ".join(deps),
                                evidence=evidence if evidence else "",
                                module_path=MODULE_PATHS[module],
                                goal=goal,
                                inp=inp,
                                outp=outp,
                            ),
                        )
                    )
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--force", action="store_true", help="overwrite existing tickets")
    args = ap.parse_args()

    written = skipped = 0
    for path, content in build():
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and not args.force:
            skipped += 1
            continue
        path.write_text(content, encoding="utf-8")
        written += 1
    print(f"wrote {written} ticket(s), skipped {skipped} existing")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
